# Generated by Django 4.1.5 on 2023-02-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name='عکس')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='والد دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PROPOSAL', 'پیشنهاد'), ('COMPLAINT', 'انتقاد یا شکایات'), ('FOLLOW', 'پیگیری سفارش'), ('SERVICE', 'خدمات پس از فروش'), ('MANAGE', 'مدیریت'), ('OTHER', 'سایر موضوعات')], max_length=100, verbose_name='عنوان')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.BigIntegerField(verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='نام محصول')),
                ('english_name', models.CharField(db_index=True, max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاک محصول')),
                ('brand', models.CharField(max_length=100, verbose_name='برند محصول')),
                ('guarantee', models.PositiveIntegerField(verbose_name='گارانتی محصول')),
                ('available', models.BooleanField(default=True, verbose_name='موجود است؟')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('price_after_discount', models.PositiveIntegerField(default=0, verbose_name='قیمت بعد از تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('discount', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('discount_time', models.DateTimeField(verbose_name='تخفیف تا تاریخ')),
                ('delivery', models.PositiveIntegerField(verbose_name='تحویل چند روزه؟')),
                ('number_sold', models.BigIntegerField(default=0, verbose_name='تعداد فروخته شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='جزئیات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.technicaldescription', verbose_name='والد جزئیات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_descriptions', to='shop.product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'مشخصات فنی',
                'verbose_name_plural': 'مشخصات فنی',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('detail', models.CharField(max_length=100, verbose_name='جزئیات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='shop.product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='مجصول مربوطه')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('detail', tinymce.models.HTMLField(verbose_name='جزئیات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='shop.product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان نظر')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='متن نظر')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('not accepted', 'تایید نشده')], default='waiting', max_length=50, verbose_name='وضعیت')),
                ('offer_vote', models.BooleanField(default=False, verbose_name='پیشنهاد میشود؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='محصول مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظر ها',
                'ordering': ('-created_on',),
            },
        ),
    ]
